In [4]:
import pandas as pd
pd.__version__

'2.2.2'

In [7]:
!curl -o laptops.csv https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  291k  100  291k    0     0  1561k      0 --:--:-- --:--:-- --:--:-- 1619k


In [8]:
df = pd.read_csv("laptops.csv")

In [10]:
num_records = len(df)

print(num_records)


2160


In [14]:
num_brands = df["Brand"].nunique()
print(num_brands)


27


In [15]:
brands = df["Brand"]

In [19]:
df.isnull().any()

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

In [17]:
num_columns_with_missing_values = df.isnull().sum()[df.isnull().sum() > 0].count()
print(num_columns_with_missing_values)


3


In [22]:
max_dell_price = df[df["Brand"] == "Dell"]["Final Price"].max()
print(max_dell_price)

3936.0


In [23]:
df["Screen"].median()

15.6

In [29]:
most_frequent_value = df["Screen"].mode()[0]
print(most_frequent_value)

15.6


In [30]:
df["Screen"] = df["Screen"].fillna(most_frequent_value)

In [32]:
df["Screen"].isna().sum()

0

In [31]:
df["Screen"].median()

15.6

In [33]:
innjoo = df[df["Brand"] == "Innjoo"]

In [35]:
innjoo_columns = innjoo[["RAM", "Storage", "Screen"]]

In [36]:
innjoo_columns

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [38]:
X = innjoo_columns.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [42]:
import numpy as np
XTX = np.matmul(X.T, X)

In [50]:
inverse = np.linalg.inv(XTX)
inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [51]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [45]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [54]:
z = np.matmul(np.matmul(inverse, X.T), y)
z

array([45.58076606,  0.42783519, 45.29127938])

In [55]:
z.sum()

91.29988062995588